test:
  workers:
    type: local
    number: 5
  rounds:
    - label: init
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: query
      txDuration: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/samples/fabric/marbles/query.js
